version: 1

before:
  hooks:
    - go generate ./cmd/rinku/...

builds:
  - main: ./cmd/rinku
    binary: rinku
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: marvai-dev
    name: rinku

brews:
  - name: rinku
    homepage: https://github.com/marvai-dev/rinku
    description: "CLI tool that finds Rust equivalents for Go libraries"
    license: "FSL-1.1-MIT"
    repository:
      owner: marvai-dev
      name: homebrew-rinku
