// Generator for precompiled index
// Run with: go run ./cmd/generate
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// MappingsFile represents the root structure of mappings.json
type MappingsFile struct {
	Description string    `json:"description"`
	Mappings    []Mapping `json:"mappings"`
}

// Mapping represents a directional library mapping entry
type Mapping struct {
	SourceLang string   `json:"source_lang"`
	TargetLang string   `json:"target_lang"`
	Category   string   `json:"category"`
	Source     string   `json:"source"`
	Target     []string `json:"target"`
	Disabled   string   `json:"disabled,omitempty"`
}

func main() {
	// Read mappings.json (go:generate runs from src/ directory)
	data, err := os.ReadFile("mappings.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading mappings.json: %v\n", err)
		os.Exit(1)
	}

	var mappingsFile MappingsFile
	if err := json.Unmarshal(data, &mappingsFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing mappings.json: %v\n", err)
		os.Exit(1)
	}

	// Build indexes using the extracted function
	index, indexAll, disabledCount := BuildIndexes(mappingsFile.Mappings)

	// Generate Go source file
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate. DO NOT EDIT.\n")
	sb.WriteString("package main\n\n")

	// Write enabled-only index
	sb.WriteString("// index maps \"target_lang:normalized_url\" to target URLs (enabled only)\n")
	sb.WriteString("var index = map[string][]string{\n")
	writeMap(&sb, index)
	sb.WriteString("}\n\n")

	// Write all-entries index (including disabled)
	sb.WriteString("// indexAll maps \"target_lang:normalized_url\" to target URLs (including disabled)\n")
	sb.WriteString("var indexAll = map[string][]string{\n")
	writeMap(&sb, indexAll)
	sb.WriteString("}\n")

	// Write output file (go:generate runs from src/ directory)
	if err := os.WriteFile("index_gen.go", []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing index_gen.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated index_gen.go with %d entries (%d disabled)\n", len(indexAll), disabledCount)
}

// writeMap writes a map to the string builder in sorted order
func writeMap(sb *strings.Builder, m map[string][]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		targets := m[key]
		sb.WriteString(fmt.Sprintf("\t%q: {", key))
		for i, t := range targets {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", t))
		}
		sb.WriteString("},\n")
	}
}
